CREATE TABLE IF NOT EXISTS portfolio_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(512) NOT NULL DEFAULT '',
  technologies JSON NOT NULL,
  url_demo VARCHAR(512) NOT NULL DEFAULT '',
  url_github VARCHAR(512) NOT NULL DEFAULT '',
  demo_user VARCHAR(255) NOT NULL DEFAULT '',
  demo_password VARCHAR(255) NOT NULL DEFAULT '',
  roles VARCHAR(512) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
